# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JarzRover Android CI

on:
  push:
    branches: [ master, jarz-development ]
    paths:
    - 'android/**'
    - '.github/workflows/gradle.yml'
  pull_request:
    branches: [ master, jarz-development ]
    paths:
    - 'android/**'
    - '.github/workflows/gradle.yml'

jobs:
  build:
    name: Gradle Checks
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: android
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build robot variants and controller
        run: ./gradlew :robot:assembleStandardDebug :robot:assembleMakerFaireDebug :controller:assembleDebug
      - name: Test robot variants
        run: ./gradlew :robot:testStandardDebugUnitTest :robot:testMakerFaireDebugUnitTest
      - name: Upload JarzRover robot apps
        uses: actions/upload-artifact@v4
        with:
          name: jarzrover-robot-debug-apks
          path: android/robot/build/outputs/apk/**/debug/*.apk
      - name: Upload JarzRover controller app
        uses: actions/upload-artifact@v4
        with:
          name: jarzrover-controller-debug-apk
          path: android/controller/build/outputs/apk/debug/*.apk
